
services:
  eureka:
    hostname: eureka-server
    build:
      context: ./server/eureka-server
      dockerfile: Dockerfile
    image: jinpold/eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - ggun-network
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:8761/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 10s
      timeout: 10s
      retries: 5


  gateway:
    hostname: gateway-server
    build:
      context: ./server/gateway-server
      dockerfile: Dockerfile
    image: jinpold/gateway:latest
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      - ggun-network
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://eureka:8000/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 10s
      timeout: 10s
      retries: 5

  account:
    hostname: account-service
    build:
      context: ./service/account-service
      dockerfile: Dockerfile
    image: jinpold/account:latest
    container_name: account
    ports:
      - "8082:8082"
    depends_on:
      gateway:
        condition: service_healthy
      eureka:
        condition: service_healthy
    networks:
      - ggun-network

  admin:
    hostname: admin-service
    build:
      context: ./service/admin-service
      dockerfile: Dockerfile
    image: jinpold/admin:latest
    container_name: admin
    ports:
      - "8081:8081"
    depends_on:
      gateway:
        condition: service_healthy
      eureka:
        condition: service_healthy
    networks:
      - ggun-network

  chat:
    hostname: chat-service
    build:
      context: ./service/chat-service
      dockerfile: Dockerfile
    image: jinpold/chat:latest
    container_name: chat
    ports:
      - "8090:8090"
    depends_on:
      gateway:
        condition: service_healthy
      eureka:
        condition: service_healthy
    networks:
      - ggun-network

  alarm:
    hostname: alarm-service
    build:
      context: ./service/alarm-service
      dockerfile: Dockerfile
    image: jinpold/alarm:latest
    container_name: alarm
    ports:
      - "8091:8091"
    depends_on:
      gateway:
        condition: service_healthy
      eureka:
        condition: service_healthy
    networks:
      - ggun-network

  user:
    hostname: user-service
    build:
      context: ./service/user-service
      dockerfile: Dockerfile
    image: jinpold/user:latest
    container_name: user
    ports:
      - "8083:8083"
    depends_on:
      gateway:
        condition: service_healthy
      eureka:
        condition: service_healthy
    networks:
      - ggun-network

networks:
  ggun-network:
    driver: bridge