apiVersion: v1
kind: Service
metadata:
  name: ggun-service
  labels:
    app: ggun
spec:
  type: LoadBalancer
  ports:
    - name: gateway
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: eureka
      protocol: TCP
      port: 8761
      targetPort: 8761
    - name: user
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: chat
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: alarm
      protocol: TCP
      port: 8091
      targetPort: 8091
    - name: admin
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: account
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    app: ggun